# Generated by Django 3.0.7 on 2020-07-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200706_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('T', 'Trade Request'), ('F', 'Friend Request')], default='T', max_length=1)),
                ('noti_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_from', to='main_app.Profile')),
                ('noti_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_to', to='main_app.Profile')),
            ],
        ),
    ]
