# Generated by Django 3.0.7 on 2020-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], default=2, max_length=1),
        ),
    ]
