# Generated by Django 3.0.7 on 2020-07-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200707_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('N', 'None'), ('C', 'Challenger'), ('D', 'Defender')], default='N', max_length=1)),
                ('shot', models.CharField(choices=[('L', 'Left'), ('H', 'Hit'), ('R', 'Right')], default='L', max_length=1)),
                ('turn', models.CharField(choices=[('C', 'Challenger')], default='C', max_length=1)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='main_app.Profile')),
                ('challenger_cb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_cb', to='main_app.Crazybone')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='main_app.Profile')),
                ('defender_cb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_cb', to='main_app.Crazybone')),
            ],
        ),
    ]
