# Generated by Django 3.0.7 on 2020-07-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_battle_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='created_notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Notification'),
        ),
    ]
