# Generated by Django 3.0.6 on 2020-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_traderequest_created_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('T', 'Trade Request'), ('F', 'Friend Request'), ('B', 'Battle Request'), ('M', 'Battle Move')], default='T', max_length=1),
        ),
    ]
