# Generated by Django 3.0.8 on 2020-07-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_profile_cb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cb2Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('cb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Crazybone')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cb',
            field=models.ManyToManyField(through='main_app.cb2Profile', to='main_app.Crazybone'),
        ),
    ]
