# Generated by Django 3.0.7 on 2020-07-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_notification_notif_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cb2Profile',
            new_name='Cb_Profile',
        ),
        migrations.AddField(
            model_name='battle',
            name='created_notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Notification'),
        ),
    ]
