# Generated by Django 3.0.7 on 2020-07-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200709_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
